CREATE SCHEMA VSB;

CREATE TABLE VSB.PRODUCT (
  ID INTEGER NOT NULL,
  NAME VARCHAR2(255) NOT NULL,
  DESCRIPTION VARCHAR2(255) NOT NULL,
  PRICE FLOAT NOT NULL,

  CONSTRAINT PRODUCT_PK PRIMARY KEY (ID)
);

CREATE SEQUENCE VSB.PRODUCT_SEQ START WITH 1 INCREMENT BY 1;
