CREATE SCHEMA VSB;
SET SCHEMA VSB;

CREATE TABLE PRODUCT (
  ID INTEGER NOT NULL,
  NAME VARCHAR2(255) NOT NULL,
  DESCRIPTION VARCHAR2(255) NOT NULL,
  PRICE FLOAT NOT NULL,

  CONSTRAINT PRODUCT_PK PRIMARY KEY (ID)
);

CREATE SEQUENCE PRODUCT_SEQ START WITH 1 INCREMENT BY 1;
